[project]
name = "03-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chainlit>=2.4.400",
    "dotenv>=0.9.9",
    "openai-agents>=0.0.7",
    "python-dotenv>=1.1.0",
]
